name: Senegal CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'test/senegal'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
      - name: make release
        run: make release
      - name: Commit files
        run: |
          git update-index --add --chmod=+x ./test/senegal
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Auto commit senegal executable" -a

        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Repository Dispatch
        run: |
          curl -X POST https://api.github.com/repos/Calamity210/Senegal/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.REPO_ACCESS_TOKEN }} \
          --data '{"event_type": "make-success", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
