name: Senegal CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'test/senegal'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: sudo apt-get install apt-transport-https &&
             sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -' &&
             sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list' &&
             sudo apt-get update &&
             sudo apt-get install dart

      - uses: actions/checkout@v2
      - name: make
        run: make
      - name: make release
        run: make release
      - name: Run Tests
        run: mv ./senegal test/ && 
             chmod +x test/senegal && 
             cd test/ && 
             dart pub get && 
             dart pub run test