name: Senegal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make release
      run: make release
    - name: Repository Dispatch
      run: |
          curl -X POST https://api.github.com/repos/Calamity210/Senegal/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.REPO_ACCESS_TOKEN }} \
          --data '{"event_type": "make-success", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
